{
 "title": "Simple dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Virtual users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT max(\"value\")\nFROM \"vus\"\nWHERE $timeFilter\nGROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT sum(\"value\")\nFROM \"http_reqs\"\nWHERE $timeFilter\nGROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"value\", 95)\nFROM \"http_req_duration\"\nWHERE $timeFilter\nGROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT mean(\"value\")\nFROM \"http_req_duration\"\nWHERE $timeFilter\nGROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "Failure rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "SELECT mean(\"value\")\nFROM \"http_req_failed\"\nWHERE $timeFilter\nGROUP BY time($__interval)"
    }
   ]
  }
 ]
}