USE shift_happens;
SET NAMES utf8mb4;

-- =========================================
-- Test accounts with known passwords
-- =========================================
-- Plaintext password for all three: password123
--
-- These hashes were generated with our app's password security layers:
--   1. PEPPER  — server-side secret (from PASSWORD_PEPPER env var) prepended to the password
--   2. SALT    — random value auto-generated by BCrypt (embedded in the hash)
--   3. BCRYPT  — adaptive hashing with cost factor 10
--
-- Hash = BCrypt(pepper + "password123"), using $2a$ prefix for Java compatibility
-- The app's PepperedPasswordEncoder applies the same pepper at login time.
-- Re-generate these hashes if you change the PASSWORD_PEPPER value.
-- =========================================

-- Employee (role 2) — employee1@shift.dk
UPDATE employee
SET login_password = '$2a$10$s53B7sTK0OeOrRP/VmrT6uZhMrmAOQXUxN/Rle/1aLnlgM4iobIx6'
WHERE employee_id = 1;

-- Manager (role 3) — employee30@shift.dk
UPDATE employee
SET login_password = '$2a$10$s53B7sTK0OeOrRP/VmrT6uZhMrmAOQXUxN/Rle/1aLnlgM4iobIx6'
WHERE employee_id = 30;

-- Administrator (role 1) — new account
INSERT INTO employee (employee_number, first_name, last_name, email, login_password,
                      user_role, phone_number, hire_date, employment_status,
                      primary_work_location_id)
VALUES ('ADM00001', 'Admin', 'User', 'admin@shift.dk',
        '$2a$10$s53B7sTK0OeOrRP/VmrT6uZhMrmAOQXUxN/Rle/1aLnlgM4iobIx6',
        'Administrator', '+45 00000001', CURDATE(), 'ACTIVE', 1);
